FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages 
COPY ./bun.lockb ./bun.lockb

COPY ./package.json ./package.json
COPY turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

COPY . .

RUN bun install
RUN bun run generate:db

EXPOSE 8080

CMD ["bun", "start:backend"]
